import type {
  Customer,
  InventoryItem,
  Insight,
  Product,
  Sale,
} from '../types'

export const customers: Customer[] = [
  {
    id: 1,
    name: 'Distribuciones Andinas',
    email: 'ventas@andinas.pe',
    phone: '987 654 321',
    city: 'Lima',
    purchases: 42,
    status: 'Activo',
  },
  {
    id: 2,
    name: 'Comercial Rivera',
    email: 'contacto@rivera.pe',
    phone: '986 321 456',
    city: 'Callao',
    purchases: 31,
    status: 'Activo',
  },
  {
    id: 3,
    name: 'Grupo Nova',
    email: 'compras@nova.pe',
    phone: '985 741 258',
    city: 'Lima',
    purchases: 27,
    status: 'Activo',
  },
  {
    id: 4,
    name: 'Inversiones Sur',
    email: 'admin@sur.pe',
    phone: '984 852 963',
    city: 'Arequipa',
    purchases: 18,
    status: 'Activo',
  },
  {
    id: 5,
    name: 'Comercial Pacífico',
    email: 'ventas@pacifico.pe',
    phone: '983 147 852',
    city: 'Trujillo',
    purchases: 11,
    status: 'Inactivo',
  },
]

export const products: Product[] = [
  {
    id: 1,
    name: 'Laptop Business Pro',
    category: 'Tecnología',
    price: 2899,
    stock: 24,
    sold: 86,
    status: 'Disponible',
  },
  {
    id: 2,
    name: 'Monitor 24"',
    category: 'Tecnología',
    price: 799,
    stock: 17,
    sold: 64,
    status: 'Disponible',
  },
  {
    id: 3,
    name: 'Teclado Mecánico',
    category: 'Accesorios',
    price: 249,
    stock: 7,
    sold: 51,
    status: 'Stock bajo',
  },
  {
    id: 4,
    name: 'Mouse Profesional',
    category: 'Accesorios',
    price: 159,
    stock: 4,
    sold: 73,
    status: 'Stock bajo',
  },
  {
    id: 5,
    name: 'Webcam Full HD',
    category: 'Accesorios',
    price: 329,
    stock: 0,
    sold: 38,
    status: 'Agotado',
  },
]

export const sales: Sale[] = [
  {
    id: 'V-00152',
    customer: 'Distribuciones Andinas',
    seller: 'Carlos Rivera',
    date: '01/10/2026',
    items: 4,
    total: 4280,
    payment: 'Completado',
  },
  {
    id: 'V-00151',
    customer: 'Grupo Nova',
    seller: 'María Torres',
    date: '01/10/2026',
    items: 2,
    total: 1598,
    payment: 'Completado',
  },
  {
    id: 'V-00150',
    customer: 'Comercial Rivera',
    seller: 'Carlos Rivera',
    date: '30/09/2026',
    items: 6,
    total: 5375,
    payment: 'Completado',
  },
  {
    id: 'V-00149',
    customer: 'Inversiones Sur',
    seller: 'Lucía Vega',
    date: '30/09/2026',
    items: 1,
    total: 2899,
    payment: 'Completado',
  },
  {
    id: 'V-00148',
    customer: 'Comercial Pacífico',
    seller: 'María Torres',
    date: '29/09/2026',
    items: 3,
    total: 1179,
    payment: 'Completado',
  },
]

export const inventory: InventoryItem[] = [
  {
    id: 1,
    product: 'Laptop Business Pro',
    category: 'Tecnología',
    stock: 24,
    minimum: 10,
    movement: '+12',
    updated: 'Hoy 08:30',
  },
  {
    id: 2,
    product: 'Monitor 24"',
    category: 'Tecnología',
    stock: 17,
    minimum: 10,
    movement: '-4',
    updated: 'Hoy 08:10',
  },
  {
    id: 3,
    product: 'Teclado Mecánico',
    category: 'Accesorios',
    stock: 7,
    minimum: 8,
    movement: '-5',
    updated: 'Ayer 18:25',
  },
  {
    id: 4,
    product: 'Mouse Profesional',
    category: 'Accesorios',
    stock: 4,
    minimum: 8,
    movement: '-7',
    updated: 'Ayer 17:48',
  },
  {
    id: 5,
    product: 'Webcam Full HD',
    category: 'Accesorios',
    stock: 0,
    minimum: 5,
    movement: '-3',
    updated: 'Ayer 15:32',
  },
]

export const insights: Insight[] = [
  {
    id: 1,
    title: 'Ventas concentradas en tecnología',
    description:
      'La categoría Tecnología representa la mayor participación de las ventas del periodo analizado.',
    metric: '48.6%',
    category: 'Ventas',
    type: 'positive',
  },
  {
    id: 2,
    title: 'Productos con stock bajo',
    description:
      'Existen productos cuya disponibilidad está por debajo del stock mínimo configurado.',
    metric: '2 productos',
    category: 'Inventario',
    type: 'warning',
  },
  {
    id: 3,
    title: 'Clientes recurrentes',
    description:
      'Los principales clientes concentran una parte importante de las compras registradas.',
    metric: '73%',
    category: 'Clientes',
    type: 'info',
  },
  {
    id: 4,
    title: 'Ticket promedio estable',
    description:
      'El valor medio de las ventas se mantiene alrededor del promedio mensual calculado.',
    metric: 'S/ 2,266',
    category: 'Ventas',
    type: 'positive',
  },
]
